---
- name: Power off vm
  hosts: localhost

  tasks:
    - name: Set powerstate of a virtual machine to poweroff by using UUID
      vmware_guest:
        hostname: {{ vcenter_hostname }}
        username: {{ vcenter_username }}
        password: {{ vcenter_password }}
        validate_certs: no
        uuid: {{ vm_uuid }}
        state: poweredoff
      delegate_to: localhost
